server:
  port: 8888

spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/config_server_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  security:
    user:
      name: admin
      password: secret
  application:
    name: config-server
  profiles:
    active: jdbc
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT key, value FROM config_properties
            WHERE application like ?
            AND profile like ? AND label like ?;
          order: 1
        bootstrap: true
        native:
          search-locations: classpath:/config

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
